# Generated by Django 4.1.2 on 2024-05-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_admin_categoria_cliente_factura_facturaproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='catg_prod',
            new_name='precio',
        ),
    ]
