# Generated by Django 4.1.2 on 2024-05-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_rename_catg_prod_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
