# Generated by Django 5.0.6 on 2024-06-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_remove_producto_imagen_url_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('hora_entrega', models.TimeField()),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='alumnos.estado')),
                ('usuario', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='alumnos.cliente')),
            ],
        ),
    ]
