# Generated by Django 4.1.2 on 2024-06-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_estado_reparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateTimeField(auto_now_add=True)),
                ('periodo_arriendo', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('deposito_garantia', models.IntegerField()),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='alumnos.cliente')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='alumnos.producto')),
            ],
        ),
    ]
