# Generated by Django 4.1.2 on 2024-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='bicicletas/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Montaña', 'Montaña'), ('BMX', 'BMX'), ('Urbana', 'Urbana')], max_length=50)),
            ],
        ),
    ]
