# Generated by Django 4.1.2 on 2024-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=12)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion_problema', models.TextField()),
            ],
        ),
    ]
